import { StyleSheet } from "react-native";

const colors = {
  background: "#F3F7FC",
  card: "#FFFFFF",
  navy: "#173255",
  text: "#314B68",
  muted: "#71839A",
  primary: "#2F64B7",
  primaryLight: "#EDF5FF",
  border: "#DFE7F2",
  lightBorder: "#E6EDF4",
  danger: "#A53636",
  dangerBackground: "#FFF1F1",
  success: "#24835E",
  successBackground: "#E8F7EF",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 110,
  },
  pageHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 18,
  },
  pageHeaderText: {
    flex: 1,
  },
  pageEyebrow: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.3,
  },
  pageTitle: {
    color: colors.navy,
    fontSize: 25,
    fontWeight: "900",
    marginTop: 7,
  },
  pageDescription: {
    maxWidth: 270,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 19,
    marginTop: 6,
  },
  totalCountBadge: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.primaryLight,
  },
  totalCountText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  taskTabs: {
    flexDirection: "row",
    gap: 8,
    padding: 5,
    borderWidth: 1,
    borderColor: "#DBE6F2",
    borderRadius: 12,
    backgroundColor: "#F5F8FC",
    marginBottom: 16,
  },
  taskTabButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  taskTabButtonActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 3,
  },
  taskTabText: {
    color: "#6C7F95",
    fontSize: 14,
    fontWeight: "900",
  },
  taskTabTextActive: {
    color: "#1F5FAE",
  },
  taskTabCount: {
    minWidth: 24,
    height: 22,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8F1FF",
  },
  taskTabCountActive: {
    backgroundColor: colors.primary,
  },
  taskTabCountText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  taskTabCountTextActive: {
    color: "#FFFFFF",
  },
  progressCard: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#F5F8FC",
    marginBottom: 16,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  progressLabel: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "800",
  },
  progressValue: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
  },
  progressTrack: {
    height: 10,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#E2E8F0",
  },
  progressBar: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  card: {
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: colors.card,
    marginBottom: 18,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 3,
  },
  sectionTitle: {
    color: colors.navy,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 8,
  },
  taskList: {
    gap: 4,
  },
  taskItem: {
    minHeight: 84,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 13,
    borderLeftWidth: 4,
    borderLeftColor: "transparent",
    borderBottomWidth: 1,
    borderBottomColor: "#EEF2F7",
    borderRadius: 10,
  },
  taskItemSelected: {
    borderLeftColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  taskItemCompleted: {
    opacity: 0.62,
  },
  taskItemPressed: {
    opacity: 0.72,
  },
  taskCheck: {
    width: 25,
    height: 25,
    flexShrink: 0,
    borderWidth: 2,
    borderColor: "#CBD5E1",
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  taskCheckActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  taskCheckDot: {
    width: 4,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#CBD5E1",
  },
  taskTextArea: {
    flex: 1,
    minWidth: 0,
  },
  taskTitle: {
    color: "#1E293B",
    fontSize: 15,
    fontWeight: "800",
  },
  taskTitleCompleted: {
    color: "#94A3B8",
    textDecorationLine: "line-through",
  },
  taskMeta: {
    color: "#71839A",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  taskStatusRow: {
    flexDirection: "row",
    marginTop: 7,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.primaryLight,
  },
  statusBadgeCompleted: {
    backgroundColor: colors.successBackground,
  },
  statusBadgeText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: "900",
  },
  statusBadgeTextCompleted: {
    color: colors.success,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 42,
    gap: 10,
  },
  emptyStateText: {
    color: "#8495A8",
    fontSize: 13,
    fontWeight: "700",
  },
  detailHeader: {
    marginBottom: 18,
  },
  detailEyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  detailTitle: {
    color: colors.navy,
    fontSize: 22,
    fontWeight: "900",
    marginTop: 6,
  },
  detailDescription: {
    color: "#72839A",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 19,
    marginTop: 7,
  },
  referenceCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#DCE8F3",
    borderRadius: 12,
    backgroundColor: "#F9FBFE",
    marginBottom: 18,
  },
  infoItem: {
    width: "50%",
    minHeight: 70,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.lightBorder,
  },
  infoItemWide: {
    width: "100%",
    paddingHorizontal: 13,
    paddingVertical: 13,
  },
  infoLabel: {
    color: "#7D8EA2",
    fontSize: 11,
    fontWeight: "800",
  },
  infoValue: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
    marginTop: 5,
  },
  infoValueMultiline: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 6,
  },
  inputLabel: {
    color: "#536B86",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 8,
  },
  textArea: {
    minHeight: 125,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#D7E3EF",
    borderRadius: 10,
    color: "#334E6D",
    backgroundColor: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 21,
    marginBottom: 15,
  },
  textAreaDisabled: {
    color: "#71849A",
    backgroundColor: "#F5F8FB",
  },
  inspectionButtons: {
    flexDirection: "row",
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: colors.primary,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  dangerButton: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#D05656",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: colors.dangerBackground,
  },
  dangerButtonText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: "800",
  },
  buttonPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  uploadHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  photoCountBadge: {
    minWidth: 32,
    height: 25,
    paddingHorizontal: 8,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF2FF",
  },
  photoCountText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 18,
  },
  photoPreview: {
    position: "relative",
    width: 86,
    height: 86,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#DBE4F0",
    borderRadius: 9,
    backgroundColor: "#F8FAFC",
  },
  photoImageButton: {
    width: "100%",
    height: "100%",
  },
  photoImage: {
    width: "100%",
    height: "100%",
  },
  deletePhotoButton: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 23,
    height: 23,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.78)",
  },
  addPhotoButton: {
    width: 86,
    height: 86,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#B7CFF6",
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FBFF",
  },
  addPhotoText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
  },
  submitActionButton: {
    minHeight: 50,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
  },
  submitActionButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  completedMessage: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#B9DFCC",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.successBackground,
  },
  completedMessageText: {
    color: colors.success,
    fontSize: 14,
    fontWeight: "800",
  },
  imageModal: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(15, 23, 42, 0.88)",
  },
  modalImage: {
    width: "100%",
    height: "80%",
  },
  modalCloseButton: {
    position: "absolute",
    top: 55,
    right: 22,
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.18)",
  },
});
